--- 
version: "3.7"
services:
    flask_app:
        container_name: flask_app
        env_file: ./.env
        build:
            dockerfile: ./Dockerfile
        image: flask_app:latest
        links:
        - postgres
        ports:
        - "5000:5000"
   
    postgres:
      image: postgres:latest
      env_file: ./.env
      volumes:
          - postgres:/var/lib/postgresql/data
      restart: always
      ports:
          - 5432:5432
      networks:
          - default
volumes:
    postgres:
        name: inspectordb