--- 
version: "3.7"
services:
    chrome:
      platform: linux/x86_64
      build:
        context: chrome/
      ports:
        - 9222:9222
    flask_app:
      image: flask_app:latest
      container_name: flask_app
      platform: linux/x86_64
      env_file: ./.env
      build:
        dockerfile: ./Dockerfile
      links:
        - postgres
      depends_on:
        - postgres
        - chrome
      ports:
        - 8500:8500
   
    postgres:
      image: postgres:latest
      env_file: ./.env
      volumes:
        - postgres:/var/lib/postgresql/data
      restart: always
      ports:
        - 5432:5432
      networks:
        - default
volumes:
    postgres:
        name: inspectordb