--- 
version: "3.7"
services:
    flask_app:
      image: flask_app:latest
      container_name: flask_app
      env_file: ./.env
      build:
        dockerfile: ./Dockerfile
      links:
        - postgres
      depends_on:  # This service depends on postgres. Start that first.
        - postgres
        - chrome
      ports:
        - 8500:8500
   
    postgres:
      image: postgres:latest
      env_file: ./.env
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        - postgres:/var/lib/postgresql/data
   
   
   
      restart: always
      ports:
        - 5432:5432
      networks:
        - default
volumes:
    postgres:
        name: inspectordb