version: '3.7'
    postgres:
      image: postgres:latest
      env_file: database.conf
      volumes:
          - postgres:/var/lib/postgresql/data
      restart: always
      ports:
          - 5432:5432
      networks:
          - default
volumes:
    postgres:
        name: inspectordb