"""empty message

Revision ID: 320c966ddd67
Revises: 
Create Date: 2022-07-20 14:53:43.501308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '320c966ddd67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrapers', sa.Column('status', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'scrapers', ['url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scrapers', type_='unique')
    op.drop_column('scrapers', 'status')
    # ### end Alembic commands ###
