"""Initial migration.

Revision ID: 368f0b913431
Revises: a2c056cb9aaf
Create Date: 2022-07-14 12:29:41.173303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368f0b913431'
down_revision = 'a2c056cb9aaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screenshots', sa.Column('name', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'screenshots', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'screenshots', type_='unique')
    op.drop_column('screenshots', 'name')
    # ### end Alembic commands ###
