"""Initial migration.

Revision ID: 46ceb6980d2b
Revises: 
Create Date: 2022-07-12 07:53:46.769872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46ceb6980d2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('article_number', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'webshops', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'webshops', type_='unique')
    op.drop_column('products', 'article_number')
    # ### end Alembic commands ###
