"""empty message

Revision ID: 9c3f702749a1
Revises: 46ceb6980d2b
Create Date: 2022-07-13 11:01:33.559618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c3f702749a1'
down_revision = '46ceb6980d2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screenshots', sa.Column('name', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'screenshots', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'screenshots', type_='unique')
    op.drop_column('screenshots', 'name')
    # ### end Alembic commands ###
