"""Initial migration.

Revision ID: a2c056cb9aaf
Revises: 
Create Date: 2022-07-14 12:08:20.312719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2c056cb9aaf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screenshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screenshot_file', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('isAdmin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('webshops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('article_number', sa.String(length=255), nullable=True),
    sa.Column('price_current', sa.Float(), nullable=False),
    sa.Column('price_reference', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('webshop_id', sa.Integer(), nullable=False),
    sa.Column('screenshot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['screenshot_id'], ['screenshots.id'], ),
    sa.ForeignKeyConstraint(['webshop_id'], ['webshops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_webshops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('webshop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['webshop_id'], ['webshops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_webshops')
    op.drop_table('products')
    op.drop_table('webshops')
    op.drop_table('users')
    op.drop_table('screenshots')
    # ### end Alembic commands ###
